version: "3.9"
services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: shm-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: shm-nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
